### ISSUE TITLE
Some To4W Random Suffix IDs are incorrect

### ISSUE THREAD

**Issue by skyler-code** [snowflame0/AtlasLootClassic_Cata#109]
**Module:** AtlasLootClassic
**Category:** Token_Data.CATA
**Loottable:**
**Items:** Sky Strider Belt/Greaves

**Additional context**
We actually got a weaker form of those random enchants
Leg IDs should be 
Earthshaker - 173
Landslide - 174
Earthfall - 175
Faultline - 176
![image](https://github.com/user-attachments/assets/9770ff16-3985-471e-a6b8-aaeb9658b6c9)

Belt IDs should be
Earthshaker - 220
Landslide - 221
Earthfall - 222
Faultline - 223

![image](https://github.com/user-attachments/assets/f91f5096-d9be-4598-b062-7e829e7cafbd)

**Comment by snowflame0** [comment]
Nice catch. Wonder if you know of any others? I guess I can check them all when I have time.

I'll push an update to ptr branch and release on reset

**Comment by snowflame0** [comment]
Looks like all the belt and leg items had mismatched suffix IDs.
Should be fixed with commit 89e0fbb
Closing.
