### ISSUE TITLE
Enchanting Rings - Cata

### ISSUE THREAD

**Issue by Raina1007** [snowflame0/AtlasLootClassic_Cata#11]
**AtlasLoot version**
v4.0.0-alpha5
**Describe the bug**
Ring Enchant not displaying 
**To Reproduce**
If you go to Cata - Enchanting - Rings: Screen is blank, but if you mouse over it the tooltip info displays
**Expected behavior**
To display the enchant, mats, how much of a stat is provided when done
**Screenshots**
<img width="963" alt="Screenshot 2024-05-27 at 7 53 01 PM" src="https://github.com/snowflame0/AtlasLootClassic_Cata/assets/72997449/acf5bb1b-8e4e-44f8-ab04-a2657fad2a75">

**Additional context**

**Comment by gitenarra** [comment]
@Raina1007 pull request with fix already created

**Comment by snowflame0** [comment]
Yep, it has been fixed. Thanks @gitenarra
