### ISSUE TITLE
Firelands Bug

### ISSUE THREAD

**Issue by Raina1007** [snowflame0/AtlasLootClassic_Cata#115]
**AtlasLoot version**
4.2.0
**Lua error**
2x ...faceAtlasLootClassic/Button/Faction_type.lua:342: bad argument #1 to 'SetJustifyV' (Usage: self:SetJustifyV(justifyV))
[string "=[C]"]: in function `SetJustifyV'
[string "@AtlasLootClassic/Button/Faction_type.lua"]:342: in function `ShowToolTipFrame'
[string "@AtlasLootClassic/Button/Faction_type.lua"]:221: in function `OnEnter'
[string "@AtlasLootClassic/Button/Button.lua"]:125: in function <AtlasLootClassic/Button/Button.lua:118>

Locals:
(*temporary) = AtlasLoot-FactionToolTip-standingText {
 0 = <userdata>
}
(*temporary) = "CENTER"

**Describe the bug**
I have bugsack/buggrabber running and it is one of the ones that popped up for me 
**To Reproduce**
Just install atlasloot, login to cata, have bugsack/buggrabber installed. 
**Expected behavior**
I'm not seeing anything specific and atlasloot is working, but something got triggered
**Screenshots**

**Additional context**

**Comment by Raina1007** [comment]
1x AtlasLootClassic/Addons/Favourites.lua:830: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: ?
[string "@AtlasLootClassic/Addons/Favourites.lua"]:830: in function `CountFavouritesByList'
[string "@AtlasLootClassic/Addons/Favourites.lua"]:814: in function `CountFavouritesByList'
[string "@AtlasLootClassic/GUI/GUI.lua"]:753: in function `?'
[string "@AtlasLootClassic/Loader.lua"]:89: in function <AtlasLootClassic/Loader.lua:77>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@AtlasLootClassic/Loader.lua"]:203: in function `LoadModule'
[string "@AtlasLootClassic/GUI/GUI.lua"]:849: in function `ButtonOnClick'
[string "@AtlasLootClassic/GUI/Template_DropDown.lua"]:159: in function `SetSelected'
[string "@AtlasLootClassic/GUI/Template_DropDown.lua"]:230: in function <...ceAtlasLootClassic/GUI/Template_DropDown.lua:228>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Comment by Raina1007** [comment]
3x AtlasLootClassic/AtlasLoot.lua:209: attempt to concatenate upvalue 'UpdatedVersionRev' (a nil value)
[string "@AtlasLootClassic/AtlasLoot.lua"]:209: in function `SendAddonVersion'
[string "@AtlasLootClassic/AtlasLoot.lua"]:92: in function `OnInitialize'
[string "@AtlasLootClassic/AtlasLoot.lua"]:36: in function <AtlasLootClassic/AtlasLoot.lua:34>

Locals:
channel = "GUILD"
target = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = "ATLASLOOT_MSG"
(*temporary) = "#v:"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to concatenate upvalue 'UpdatedVersionRev' (a nil value)"
AtlasLoot = <table> {
 ClickHandler = <table> {
 }
 DevPrint = <function> defined @AtlasLootClassic/AtlasLoot.lua:58
 OnInitialize = <function> defined @AtlasLootClassic/AtlasLoot.lua:74
 Data = <table> {
 }
 IngameLocales = <table> {
 }
 Locale = <table> {
 }
 SendAddonVersion = <function> defined @AtlasLootClassic/AtlasLoot.lua:203
 Loader = <table> {
 }
 Addons = <table> {
 }
 db = <table> {
 }
 SlashCommands = <table> {
 }
 LibBabble = <table> {
 }
 GameVersion_LE = <function> defined @AtlasLootClassic/Init.lua:150
 dbRaw = <table> {
 }
 IS_BC = false
 dbGlobal = <table> {
 }
 GUI = <table> {
 }
 MiniMapButton = <table> {
 }
 Faction_GetFactionName = <function> defined @AtlasLootClassic/Button/Faction_type.lua:154
 CLASSIC_VERSION_NUM = 1
 ItemDB = <table> {
 }
 GameVersion_EQ = <function> defined @AtlasLootClassic/Init.lua:105
 Button = <table> {
 }
 ItemInfo = <table> {
 }
 AddInitFunc = <function> defined @AtlasLootClassic/AtlasLoot.lua:95
 ReturnForGameVersion = <function> defined @AtlasLootClassic/AtlasLoot.lua:105
 __addonversion = "3.2.0"
 TargetScan = <table> {
 }
 GetGameVersion = <function> defined @AtlasLootClassic/Init.lua:100
 Locales = <table> {
 }
 ItemQuery = <table> {
 }
 Print = <function> defined @AtlasLootClassic/AtlasLoot.lua:54
 TooltipScan = <table> {
 }
 DIFFICULTY = <table> {
 }
 Tooltip = <table> {
 }
 BC_VERSION_NUM = 2
 CURRENT_VERSION_NUM = 3
 GameVersion_GE = <function> defined @AtlasLootClassic/Init.lua:141
 GetColoredClassNames = <function> defined @AtlasLootClassic/AtlasLoot.lua:121
 IsAddonUpdateAviable = <function> defined @AtlasLootClassic/AtlasLoot.lua:212
 GetGameVersionDataTable = <function> defined @AtlasLootClassic/AtlasLoot.lua:154
 GetLocales = <function> defined @AtlasLootClassic/Locales/Locales.lua:12
 GameVersion_LT = <function> defined @AtlasLootClassic/Init.lua:132
 IS_RETAIL = false
 Init = <table> {
 }
 GetRetByFaction = <function> defined @AtlasLootClassic/AtlasLoot.lua:147
 WRATH_VERSION_NUM = 3
 RGBToHex = <function> defined @AtlasLootClassic/AtlasLoot.lua:136
 GameVersion_GT = <function> defined @AtlasLootClassic/Init.lua:123
 IS_CLASSIC = false
 IS_WRATH = true
 ItemString = <table> {
 }
 GAME_VERSION_TEXTURES = <table> {
 }
 OnProfileChanged = <function> defined @AtlasLootClassic/AtlasLoot.lua:64
 AtlasLootDBDefaults = <table> {
 }
 GameVersion_NE = <function> defined @AtlasLootClassic/Init.lua:114
 RETAIL_VERSION_NUM = 99
}
SendAddonMessage = <function> defined =[C]:-1
ALPrivate = <table> {
 CLASS_ICON_PATH_ITEM_DB = <table> {
 }
 IS_CLASSIC = false
 PRICE_ICON_REPLACE = <table> {
 }
 BOX_BACKDROP = <table> {
 }
 CLASS_ICON_PATH = <table> {
 }
 CLASS_BITS = <table> {
 }
 ACCOUNT_LOCALE = "enUS"
 LOC_CLASSES = <table> {
 }
 BOX_BORDER_BACKDROP = <table> {
 }
 IS_WOTLK = true
 IS_BC = false
 COIN_TEXTURE = <table> {
 }
 CLASS_BIT_TO_CLASS = <table> {
 }
 CLASS_NAME_TO_ID = <table> {
 }
 ADDON_MSG_PREFIX = "ATLASLOOT_MSG"
 PLAYER_NAME = "Morfyd"
 CLASS_SORT = <table> {
 }
 IMAGE_PATH = "Interface\AddOns\AtlasLootClassic\Images\"
 ICONS_PATH = "Interface\AddOns\AtlasLootClassic\Images\Icons\"
}
UpdateSendMsg = "#v:"
UpdatedVersionRev = nil

**Comment by snowflame0** [comment]
Strange... upon checking your errors it looks like you're running 5 month old versions of certain files. Please delete all AtlasLoot* folders in your Interface/Addons/ folder and reinstall 4.2.0 from scratch

**Comment by snowflame0** [comment]
Assuming fixed, open issue if you have another problem.
