### ISSUE TITLE
The dungeon sets are only present in TBC section.

### ISSUE THREAD

**Issue by Cabro** [snowflame0/AtlasLootClassic_Cata#116]
It is completely missing from Vanilla, Wotlk and Cata loot tables.

**Additional context**
![image](https://github.com/user-attachments/assets/74d95e42-a389-45be-a616-25165e0ed241)

**Comment by snowflame0** [comment]
It should only be in Classic and TBC tables, don't think there were any dungeon sets in Wrath or Cata. I can still display them on all game versions, but not sure if people care enough about old dungeon sets.. esp because some don't drop anymore afaik.
