### ISSUE TITLE
Cant download from Curse Forge

### ISSUE THREAD

**Issue by gitenarra** [snowflame0/AtlasLootClassic_Cata#24]
**Additional context**
(https://www.curseforge.com/wow/addons/atlaslootclassic/files/all?page=1&pageSize=20&showAlphaFiles=show)
Current v4.0.0-alpha10 no available, so where can ppls download your atlasloot?
https://www.curseforge.com/members/snowflame0/projects
As I see, no project was found under your user either.

**Comment by snowflame0** [comment]
https://www.curseforge.com/wow/addons/atlaslootclassic-cata/files/all?page=1&pageSize=20&showAlphaFiles=show

Will be available in Curse client once it's in beta.
