### ISSUE TITLE
Atlas Loot wont show up on German Client 

### ISSUE THREAD

**Issue by MaleMale4k** [snowflame0/AtlasLootClassic_Cata#43]
**AtlasLoot version**
Newest: [v4.0.0-alpha12](https://github.com/snowflame0/AtlasLootClassic_Cata/tree/v4.0.0-alpha12) (2024-06-01)
**Lua error**
/
**Describe the bug**
Atlas Loot wont show up when loadet. It seems like its because im using the german language

**To Reproduce**
I Put in the up to date Version. Same Data is working on an english Client

**Expected behavior**

**Screenshots**
https://i.imgur.com/xYJ75A0.png
https://i.imgur.com/0Ht0ubD.png

**Additional context**

**Comment by snowflame0** [comment]
I've changed my client to German and can't reproduce the bug, anyone else manage to?

Please re-install the addon with the Curseforge app, maybe something isn't in the right place.
<img width="650" alt="Screen Shot 2024-06-04 at 11 54 30 PM" src="https://github.com/snowflame0/AtlasLootClassic_Cata/assets/2276311/9e91a49c-3a6d-4b8b-9b42-f56abf43e5e1">

**Comment by MaleMale4k** [comment]
![Screenshot 2024-06-05 120057](https://github.com/snowflame0/AtlasLootClassic_Cata/assets/116797932/b3423ad2-8d04-4d85-b26f-c48e4c88788a)
![Screenshot 2024-06-05 120106](https://github.com/snowflame0/AtlasLootClassic_Cata/assets/116797932/348996a2-11c5-42ff-9e2d-e93e866bf2f4)

Unfortunately no success

**Comment by MaleMale4k** [comment]
not for me :(

**Comment by scareclaw-kashtira** [comment]
If the addon isn't get picked up at all first thing to do is full restart the game

**Comment by MaleMale4k** [comment]
> If the addon isn't get picked up at all first thing to do is full restart the game

That does not help.

**Comment by snowflame0** [comment]
Let's try a few things.

First, can you take a screenshot of what is inside the "_classic_/Interface/Addons/AtlasLootClassic" folder?

Second, delete the whole folder "Cache" inside  "_classic_" 

Next, go to "_classic_/WTF/Account/<your account>", delete "cache.md5", "config-cache.wtf", and "config-cache.old"

Last, "_classic_/WTF/Account/<your account>/SavedVariables", delete "AtlasLootClassic.lua" and "AtlasLootClassic.lua.bak"

Hope one of those works.

**Comment by MaleMale4k** [comment]
That did it. <resolved>
