### ISSUE TITLE
Incorrect number of Inks in Glyph Recipes

### ISSUE THREAD

**Issue by Bisonpasfute** [snowflame0/AtlasLootClassic_Cata#44]
**Module:** Crafting
**Category:** Inscription
**Items:** Glyphs (ie. Glyph of Bloodletting)

**Additional context:**
The number of Inks that is needed to craft Glyphs is wrong on most Glyphs.

For instance with the Glyph of Bloodletting : 
![Capture d'écran 2024-06-05 124916](https://github.com/snowflame0/AtlasLootClassic_Cata/assets/35010278/d392fa5d-e03e-43c3-ab2b-4485568f18b7)

**Comment by gitenarra** [comment]
@Bisonpasfute inscription still in progress so it takes time to fix this profession

**Comment by snowflame0** [comment]
Fixed on latest commit.
