### ISSUE TITLE
v4.0.1 beta1 not working

### ISSUE THREAD

**Issue by kyjo191** [snowflame0/AtlasLootClassic_Cata#47]
v4.0.1 beta1

I installed from both github and curseforge and neither version shows up in addon list or work.
Cleared files from addon folder and reinstalled from curseforge and it still doesn't work.

https://imgur.com/a/jIKADpL

**Comment by gitenarra** [comment]
@kyjo191 can you check in addons folder if atlasloot exist?
(from battle.net wow page click on setting near play button, show in explorer-_classic_-interface-addons)

**Comment by snowflame0** [comment]
Please try the following from another similar issue:

https://github.com/snowflame0/AtlasLootClassic_Cata/issues/43#issuecomment-2153204879

**Comment by snowflame0** [comment]
Assuming it's been fixed, so closing. Reopen an issue if you still have problems.
