### ISSUE TITLE
Hunter filter does not include staves for some reason

### ISSUE THREAD

**Issue by Triksterism** [snowflame0/AtlasLootClassic_Cata#50]
**AtlasLoot version**
N/A
**Lua error**
N/A
**Describe the bug**
Hunter class filter does not include staves, which they very much can use.
**To Reproduce**
N/A
**Expected behavior**
When selecting the class filter for hunter, staves should be included in the highlight
**Screenshots**
N/A
**Additional context**

`[LE_ITEM_WEAPON_STAFF] 		    = C.DRUID + C.MAGE + C.PRIEST + C.SHAMAN + C.WARLOCK, -- Staves`

should be changed to

`[LE_ITEM_WEAPON_STAFF] 		    = C.DRUID + C.HUNTER + C.MAGE + C.PRIEST + C.SHAMAN + C.WARLOCK, -- Staves`

**Comment by snowflame0** [comment]
Should be fixed on next release, thanks for the report.
