### ISSUE TITLE
Baradin Hold - Warrior and Death Knight sets are swapped

### ISSUE THREAD

**Issue by alex47** [snowflame0/AtlasLootClassic_Cata#55]
**Module:** Dungeons and Raids
**Category:** BaradinHold
**Loottable:** Argaloth
**Items:** Warrior (Protection, Damage Dealer), Death Knight (Blood, Damage Dealer)

**Additional context**
The Warrior items are shown under the Death Knight group, and Death Knight items are shown under the Warrior group. This includes both tank, dps, and pvp items.

![image](https://github.com/snowflame0/AtlasLootClassic_Cata/assets/10761683/5b9fe550-b58a-45da-9147-daa433f37818)

**Comment by snowflame0** [comment]
Already fixed in latest dev version, will be fixed on next beta release.
