### ISSUE TITLE
Spine of Deathwing showing wrong Achievement

### ISSUE THREAD

**Issue by Darnias** [snowflame0/AtlasLootClassic_Cata#64]
**AtlasLoot version**- v4.0.1 beta3

**Lua error**- None

**Describe the bug**- Spine of Deathwing Heroic shows Ultraxion achievement

**To Reproduce**- Open Spine of Deathing heroic in atlas loot

**Expected behavior**- Show Spine of Deathwing heroic achievement

**Screenshots**- https://i.imgur.com/OO3tZOO.png

**Additional context**

**Comment by Darnias** [comment]
Opened it as wrong type of Issue label, my bad.

**Comment by snowflame0** [comment]
Should be fixed on next release.
