### ISSUE TITLE
Darkmoon Fair Items

### ISSUE THREAD

**Issue by evilgodly** [snowflame0/AtlasLootClassic_Cata#65]
**Module:**
**Category:**
**Loottable:**
**Items:**

**Additional context**
Missing the heirloom & replica items for DMF. Cant find a good place for them on wowhead but here is a place for the [heirlooms](https://www.wowhead.com/cata/guide/darkmoon-faire-updates#heirlooms-replica-armor-prizes).

**Comment by snowflame0** [comment]
Should be fixed on next release.

**Comment by snowflame0** [comment]
The heirlooms are the same as what you can get from the JP vendor right? Just another way to get them with tickets? I can add those as a secondary source.

As for the replica items, I will need to come up with a way to display them then generate those tables. I'll work on it when I have a chance.

**Comment by snowflame0** [comment]
Should be under Collections->Darkmoon Faire now, open a new issue if anything else is still missing.
