### ISSUE TITLE
set focus target get blocked from Atlas

### ISSUE THREAD

**Issue by Crckit** [snowflame0/AtlasLootClassic_Cata#67]
**AtlasLoot version** 

v4.0.1 -beta3

**Lua error**

**Describe the bug**

Setting focus target of a group member doesnt work in dungeon. When click "set focus" the action blocked Window appears.

"AtlasLootClassic has been blocked from an action only available to the Blizzard UI. You can disable this addon and reload the UI. 
Disable / Ignore

**To Reproduce**

**Expected behavior**

**Screenshots**

![Screenshot 2024-06-18 100438](https://github.com/snowflame0/AtlasLootClassic_Cata/assets/173135361/5de2d4f0-7cd4-4cef-921b-060bcf7dcb72)

**Additional context**

BugSacked Information

15x [ADDON_ACTION_BLOCKED] AddOn 'AtlasLootClassic' tried to call the protected function 'CompactRaidFrame1:SetPoint()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `SetPoint'
[string "@Blizzard_FrameXMLBase/FlowContainer.lua"]:176: in function `FlowContainer_DoLayout'
[string "@Blizzard_FrameXMLBase/FlowContainer.lua"]:17: in function `FlowContainer_ResumeUpdates'
[string "@Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua"]:185: in function `CompactRaidFrameContainer_LayoutFrames'
[string "@Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua"]:130: in function `CompactRaidFrameContainer_TryUpdate'
[string "@Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua"]:57: in function `CompactRaidFrameContainer_OnEvent'
[string "*Blizzard_CompactRaidFrameContainer.xml:79_OnEvent"]:1: in function <[string "*Blizzard_CompactRaidFrameContainer.xml:79_..."]:1>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:491
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:557
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:557
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:551
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:566
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:511
}

**Comment by snowflame0** [comment]
Haven't been able to reproduce, did you disable all other addons besides AtlasLoot and BugGrabber and see if it does it again?
Could be another addon that is hooking into AtlasLoot and blaming it. As far as I know AtlasLoot doesn't make any calls to raid frames.

**Comment by orionshock** [comment]
This error isn't coming from Atlas Loot - it's rando taint due to some dropdown. it's a known issue since classic.
