### ISSUE TITLE
Add ability for class filters to include armor with any stats

### ISSUE THREAD

**Issue by Triksterism** [snowflame0/AtlasLootClassic_Cata#68]
**Is your feature request related to a problem? Please describe.**
N/A
**Describe the solution you'd like**
I noticed with the recent updates if I filter for hunter, I wont see int mail or str weapons highlighted. This is nice for current content item filtering but for old content transmog hunting it's annoying. Would be nice to have a toggle perhaps.
**Additional context**

**Comment by snowflame0** [comment]
This feature already exists.
First, shift click the AtlasLoot minimap icon to open settings.
Select Class Filter -> Select your class (top right) -> mess with the checkboxes to set your preferences.
