### ISSUE TITLE
Mounts + Heirlooms need work

### ISSUE THREAD

**Issue by Firsthunterz** [snowflame0/AtlasLootClassic_Cata#69]
It seems the Mounts are all over the place currently. Missing rep mounts (camels), a few mounts listed in the wrong location, a bunch of mounts missing completely as well. (All the FL mounts, the molten front mount, DMF mounts). Cata heirlooms r missing and shows the (10H / 25 / 25H) on the display. Great job on taking over and updating though!!

**Comment by snowflame0** [comment]
Aware of this and will work on it when I have time. If anyone wants to help in the meantime, feel free to do a PR.
