### ISSUE TITLE
Crafted Items Wrong

### ISSUE THREAD

**Issue by evilgodly** [snowflame0/AtlasLootClassic_Cata#74]
Crafting > BS or LW or Tailor 

Listing items obtained from Dragon Soul & Firelands but neither of these places are released at this time. Causing confusion. Seeing this in v4.0.1-beta4

**Comment by snowflame0** [comment]
This was intended. It's how it was in the Wrath release as well. Phased content was supposed to be supported by AtlasLootClassic but we haven't implemented it for Cata and I'm not sure it was done for Wrath either.
