### ISSUE TITLE
Cata: Requirements.lua:5893 PVP Season 6 Error

### ISSUE THREAD

**Issue by evilgodly** [snowflame0/AtlasLootClassic_Cata#75]
Got this today in Classic Cata while in Dal on my 85 Fire Mage while under BC>PVP>Season 6, nothing comes up at all

7x AtlasLootClassic/Data/Requirements.lua:5893: attempt to compare table with number
[string "@AtlasLootClassic/Data/Requirements.lua"]:5893: in function `BuildClassString'
[string "@AtlasLootClassic/Data/ItemSet.lua"]:1923: in function `GetSetDescriptionString'
[string "@AtlasLootClassic/Button/Set_type.lua"]:69: in function `OnSet'
[string "@AtlasLootClassic/Button/Button.lua"]:767: in function `SetType'
[string "@AtlasLootClassic/Button/Button.lua"]:734: in function `SetContentTable'
[string "@AtlasLootClassic/GUI/ItemFrame.lua"]:199: in function `Refresh'
[string "@AtlasLootClassic/GUI/GUI.lua"]:196: in function <AtlasLootClassic/GUI/GUI.lua:48>
[string "@AtlasLootClassic/GUI/GUI.lua"]:1044: in function `ButtonOnClick'
[string "@AtlasLootClassic/GUI/Template_Select.lua"]:90: in function `SetSelected'
[string "@AtlasLootClassic/GUI/Template_Select.lua"]:137: in function `SetData'
[string "@AtlasLootClassic/GUI/GUI.lua"]:981: in function `ButtonOnClick'
[string "@AtlasLootClassic/GUI/Template_Select.lua"]:90: in function `SetSelected'
[string "@AtlasLootClassic/GUI/Template_Select.lua"]:137: in function `SetData'
[string "@AtlasLootClassic/GUI/GUI.lua"]:938: in function `ButtonOnClick'
[string "@AtlasLootClassic/GUI/Template_DropDown.lua"]:159: in function `SetSelected'
[string "@AtlasLootClassic/GUI/Template_DropDown.lua"]:230: in function <...ceAtlasLootClassic/GUI/Template_DropDown.lua:228>

Locals:
classBit = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare table with number"
ClassStrings = <table> {
 1 = "|TInterface\AddOns\AtlasLootClassic\Images\Icons\classicon_warrior:0|t "
 2 = "|TInterface\AddOns\AtlasLootClassic\Images\Icons\classicon_paladin:0|t "
 4 = "|TInterface\AddOns\AtlasLootClassic\Images\Icons\classicon_hunter:0|t "
 64 = "|TInterface\AddOns\AtlasLootClassic\Images\Icons\classicon_shaman:0|t "
 256 = "|TInterface\AddOns\AtlasLootClassic\Images\Icons\classicon_warlock:0|t "
 1024 = "|TInterface\AddOns\AtlasLootClassic\Images\Icons\classicon_druid:0|t "
 32 = "|TInterface\AddOns\AtlasLootClassic\Images\Icons\classicon_deathknight:0|t "
 128 = "|TInterface\AddOns\AtlasLootClassic\Images\Icons\classicon_mage:0|t "
 16 = "|TInterface\AddOns\AtlasLootClassic\Images\Icons\classicon_priest:0|t "
 8 = "|TInterface\AddOns\AtlasLootClassic\Images\Icons\classicon_rogue:0|t "
}
CLASS_SORT = <table> {
 1 = "WARRIOR"
 2 = "PALADIN"
 3 = "HUNTER"
 4 = "ROGUE"
 5 = "PRIEST"
 6 = "DEATHKNIGHT"
 7 = "SHAMAN"
 8 = "MAGE"
 9 = "WARLOCK"
 10 = "DRUID"
}
bit_band = <function> defined =[C]:-1
CLASS = <table> {
 HUNTER = 4
 WARRIOR = 1
 PALADIN = 2
 MAGE = 128
 PRIEST = 16
 WARLOCK = 256
 SHAMAN = 64
 DRUID = 1024
 DEATHKNIGHT = 32
 ROGUE = 8
}
format = <function> defined =[C]:-1
TEXTURE_STRING = "|T%s:0|t "
CLASS_ICON_PATH = <table> {
 HUNTER = "Interface\AddOns\AtlasLootClassic\Images\Icons\classicon_hunter"
 WARRIOR = "Interface\AddOns\AtlasLootClassic\Images\Icons\classicon_warrior"
 PALADIN = "Interface\AddOns\AtlasLootClassic\Images\Icons\classicon_paladin"
 MAGE = "Interface\AddOns\AtlasLootClassic\Images\Icons\classicon_mage"
 PRIEST = "Interface\AddOns\AtlasLootClassic\Images\Icons\classicon_priest"
 WARLOCK = "Interface\AddOns\AtlasLootClassic\Images\Icons\classicon_warlock"
 DEATHKNIGHT = "Interface\AddOns\AtlasLootClassic\Images\Icons\classicon_deathknight"
 DRUID = "Interface\AddOns\AtlasLootClassic\Images\Icons\classicon_druid"
 SHAMAN = "Interface\AddOns\AtlasLootClassic\Images\Icons\classicon_shaman"
 ROGUE = "Interface\AddOns\AtlasLootClassic\Images\Icons\classicon_rogue"
}

**Comment by snowflame0** [comment]
Finally looked at the issue and narrowed the problem down to a missing item level in a set, causing the issue. Should be fixed on next release.
