### ISSUE TITLE
Pets not tracking properly

### ISSUE THREAD

**Issue by Xqzmeplz** [snowflame0/AtlasLootClassic_Cata#76]
**AtlasLoot version**
v4.0.1-beta4

**Describe the bug**
The collection state "Collected" / "Not Collected" in atlasloot or inside the tooltip (if "Show learned info for companion" is enabled). Is not tracking and in some cases "wrong".

**To Reproduce**
1. use a newer pet e.g. [Darkmoon Cub]
2. Pet that is learned on a different character

**Additional context**
1. `COMPANION_DATA` should be updated and include the newest mounts / pets.
2. `COLLECTED_COMPANIONS` should use `C_PetJournal`

**Comment by snowflame0** [comment]
Merged, should be fixed on next release. Thanks again
