### ISSUE TITLE
"Show learned info for companions" option doesn't work on cata pets

### ISSUE THREAD

**Issue by Cabro** [snowflame0/AtlasLootClassic_Cata#78]
**AtlasLoot version**
4.0.1-beta4

**Describe the bug**
It fails to add the collected/not collected tooltips to cata pets.

**To Reproduce**
Learn one of the cata pets and notice no "Collected" text on it

**Expected behavior**
![image](https://github.com/user-attachments/assets/fce724fd-0a28-4c57-adf5-333821ffb03f)

**Screenshots**
![image](https://github.com/user-attachments/assets/8a037169-7e6e-4e8d-9806-cf85319a4d1c)
![image](https://github.com/user-attachments/assets/c329492e-0492-47fd-a3a3-ee5a9040e54e)

**Additional context**
-

**Comment by Firsthunterz** [comment]
https://github.com/snowflame0/AtlasLootClassic_Cata/pull/77/files   this is the fix for that if you want to download the file and replace it.

**Comment by snowflame0** [comment]
Sorry, been inactive for a couple weeks. I'll push out a new update soon. Should be ready to drop the beta tag.

**Comment by Cabro** [comment]
@Firsthunterz that fix is missing this one `  [34955] = {45890, 25706, 1}, --Scorched Stone`
