### ISSUE TITLE
Atlasloot Cata PTR does not load as expected

### ISSUE THREAD

**Issue by larion89** [snowflame0/AtlasLootClassic_Cata#82]
**AtlasLoot version**
v4.0.1
**Lua error**
Message: Interface/AddOns/AtlasLootClassic/Core/ItemInfo.lua:353: attempt to concatenate local 'name' (a nil value)
Time: Fri Sep  6 11:27:54 2024
Count: 1
Stack: Interface/AddOns/AtlasLootClassic/Core/ItemInfo.lua:353: attempt to concatenate local 'name' (a nil value)
[string "@Interface/AddOns/AtlasLootClassic/Core/ItemInfo.lua"]:353: in function `func'
[string "@Interface/AddOns/AtlasLootClassic/AtlasLoot.lua"]:42: in function <Interface/AddOns/AtlasLootClassic/AtlasLoot.lua:34>

Locals: NewLocData = <table> {
 loc = <table> {
 }
}
(for index) = 0
(for limit) = 15
(for step) = 1
iC = 0
class = <table> {
 __name = "Consumable"
 2 = "Liquid(OBSOLETE)"
 1 = "Cheese/Bread(OBSOLETE)"
 0 = "Consumable"
}
className = "Consumable"
(for index) = 1
(for limit) = 2
(for step) = 1
isC = 1
subClass = "Cheese/Bread(OBSOLETE)"
name = nil
(*temporary) = <table> {
 ConsumableConsumable = "Consumable"
 Consumable = "Consumable"
}
(*temporary) = "Consumable"
(*temporary) = nil
(*temporary) = "attempt to concatenate local 'name' (a nil value)"
LOC_DATA = <table> {
 0 = <table> {
 }
 13 = <table> {
 }
 7 = <table> {
 }
 1 = <table> {
 }
 2 = <table> {
 }
 4 = <table> {
 }
 8 = <table> {
 }
 15 = <table> {
 }
 9 = <table> {
 }
 5 = <table> {
 }
 10 = <table> {
 }
 14 = <table> {
 }
 3 = <table> {
 }
 6 = <table> {
 }
 12 = <table> {
 }
 11 = <table> {
 }
}
FILTER = <table> {
 1 = <table> {
 }
}
ItemInfo = <table> {
}

**Describe the bug**
doesnt load on Cataclysm PTR 4.4.1
**To Reproduce**
start the game, load addon
**Expected behavior**
Loads as expected.
**Screenshots**

**Additional context**

**Comment by Firsthunterz** [comment]
I swear they break addons on purpose every content patch. All my addons worked fine when PTR came online on the 3rd and they added the molten front token vendor on the 5th and broke every single addon in the process somehow.

**Comment by snowflame0** [comment]
Seems to have only been an issue on the PTR, working fine as of now, open a new issue if anything arises on live servers.
