### ISSUE TITLE
Update for Molten Front / Collections / Firelands / Dragon Soul

### ISSUE THREAD

**Issue by Firsthunterz** [snowflame0/AtlasLootClassic_Cata#85]
[Uploading AtlasLootClassic Pack.zip…]()

Multiple updates to Collections and Firelands / Dragon Soul. Added missing mounts

**Comment by Raina1007** [comment]
A few issues that will need to be sorted out. In Armor - Cloth - Mages tier chest is listed twice, missing hands - Priest(Healing) Tier chest is listed twice, missing legs.

**Comment by Firsthunterz** [comment]
I've gone through fixed these issues, new file is posted above. Also includes collections update as well as firelands and dragon soul updates
