### ISSUE TITLE
Hallow's End event incorrect ilevel loot

### ISSUE THREAD

**Issue by Draconyx84** [snowflame0/AtlasLootClassic_Cata#95]
Latest 4.1.2 release with updated Hallow's End loot seems to show ilvl 353 loot instead of 365

![image](https://github.com/user-attachments/assets/b722905a-04cb-44e6-8346-e0f2d33c02a2)
![image](https://github.com/user-attachments/assets/fa96b9e8-e938-47e2-9c39-f3e6f1894e27)

**Comment by Adal4** [comment]
Fixed in #96

**Comment by snowflame0** [comment]
Yep, looks like it was unclear what item level it would be. I'll drop another release right away.
