### ISSUE TITLE
Nefarians end, normal, tokens showing wrong loot

### ISSUE THREAD

**Issue by curedfromcancer** [snowflame0/AtlasLootClassic_Cata#98]
cataclysm>dungeons and raids>blackwing descent>nefarians end>normal.
all head tokens within this bracket are showing the shoulder drops as apposed to the heads.
https://gyazo.com/57bf3b8dea70ee5a297c868773bb5011
https://gyazo.com/50e35f273b59c71ebe53e77d1c9bdd5e
https://gyazo.com/a6a4cfe5a0668c99e7989b81ee008aba

**Comment by snowflame0** [comment]
Good catch, looks like the head and shoulder token data was swapped. Should be fixed on next release.
